Table of contents
statelyai/eng-blog pull request #58
Opened 2022-01-13 00:40 UTC by farskid

2022-01-13 12:15 UTC, farskid commented on pages/index.tsx
> +  if (process.env.NODE_ENV === "production") {
This speeds up loading the blog in dev mode up to 6 seconds!

2022-01-17 14:34 UTC, laurakalbag requested changes
Just some small accessibility comments…

2022-01-17 14:34 UTC, laurakalbag commented on src/components/Layout.tsx
> +      _hover={{
Please could we make the `opacity: 1` also work for `focus` and `active` states? (Especially important for keyboard navigation.)

2022-01-17 14:34 UTC, laurakalbag commented on pages/[slug].tsx
> +            <h2 className="toc-title">Table of contents</h2>
We can probably get away with the `h2` outside of the `nav` if we give the `h2` an `id` and use [`aria-labelledby`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-labelledby) on the `ul` or the `nav`. Is this doable, or are we unable to change anything inside the `TOC` component?

2022-01-17 14:34 UTC, laurakalbag commented on src/components/Layout.tsx
> +      opacity="0.5"
I know this’ll impact how much the toc fades into the background, but we should probably make the opacity higher so that the text is still a readable (by accessibility standards) contrast? `opacity: 0.75` produces a passable value, but does that defeat the point of changing the opacity?

2022-01-17 14:34 UTC, laurakalbag commented on src/components/Layout.tsx
> +      opacity="0.5"
Maybe we could also make the link text slightly smaller, so it’s more like the post tags? That’ll make it less visually distracting too.

2022-01-19 22:38 UTC, farskid commented on src/components/Layout.tsx
> +      _hover={{
Sure, but that wouldn't still change the opacity of it when one of the links is focused. Can we do that with CSS?

2022-01-19 23:35 UTC, farskid commented on pages/[slug].tsx
> +            <h2 className="toc-title">Table of contents</h2>
I can revert the change so that `h2` lives inside the `nav` element.

2022-01-19 23:35 UTC, farskid commented on src/components/Layout.tsx
> +      opacity="0.5"
Sure. I agree with both.

2022-01-20 11:12 UTC, laurakalbag commented on pages/index.tsx
> +  if (process.env.NODE_ENV === "production") {
🎉

2022-01-20 11:16 UTC, laurakalbag commented on src/components/Layout.tsx
> +      _hover={{
Hmm, not sure I understand. This is something we can do with CSS.

2022-01-20 11:16 UTC, laurakalbag commented on pages/[slug].tsx
> +            <h2 className="toc-title">Table of contents</h2>
Great, that’ll make it less complicated!

2022-01-20 11:17 UTC, laurakalbag commented on src/components/Layout.tsx
> +      opacity="0.5"
Yay.

2022-01-31 22:20 UTC, farskid commented on pages/[slug].tsx
> +  });
https://stately.ai/registry/machines/8cb616a7-0e79-427d-b594-d80bda3a74e1.png

2022-01-31 22:24 UTC, farskid commented on pages/[slug].tsx
> +  });
Made smooth scrolling smarter. We only enable it on the post page either after the first scroll has happened due to existing hash in the URL or after 100ms.

2022-02-01 08:30 UTC, laurakalbag approved these changes

2022-02-01 08:40 UTC, merged