Added blog post on nesting typegen files
statelyai/eng-blog pull request #87
Opened 2022-06-13 12:18 UTC by mellson

We have some [feedback from a user](https://twitter.com/MarkBennett/status/1534996099840110594?s=20&t=dmCI7kx4qPnju0t-r9hqNg) pointing out that our new nesting typegen popup in our extension could need some more info.

This PR introduces a blog post trying to explain what file nesting is. When the post is published we can link to it from our file nesting popup in our extension.

Link to the preview deploy: https://blog-88cw2ho0p-statelyai.vercel.app/blog/nesting-xstate-typegen-files

2022-06-14 11:20 UTC, laurakalbag requested changes
Most of these suggestions are nits, so feel free to ignore if they don’t work for you.

My suggestions for links and alt text are for accessibility. Links are generally more useful to folks using assistive tech if they’re understandable outside the context of the sentence. This is because a lot of assistive tech lets you browse through the links on the page as a list. And alt text doesn’t need to describe the format or purpose of the image so much as conveying the key information that the reader gains from viewing the image.

The “request changes” aspect of this review is just that I think we might benefit from some information on when the user will get the helper prompt (and maybe what to do later if they change their mind about the setting they chose?)

2022-06-14 11:20 UTC, laurakalbag commented on content/posts/2022-06-13-nesting-typegen-files.mdx
> +This is how the explorer in VS Code looks without file nesting enabled when you have a machine source file alongside a generated type file for that machine.
```suggestion
The image below shows the explorer in VS Code without file nesting enabled; you have a machine source file alongside a generated type file for that machine.
```

2022-06-14 11:20 UTC, laurakalbag commented on content/posts/2022-06-13-nesting-typegen-files.mdx
> +![VS Code explorer view with an XState machine alongside the types generated for it.](./images/without-typegen.png)
```suggestion
![The source file in the VS Code explorer called coolMachine.ts is listed above the typegen file called coolMachine.typegen.ts.](./images/without-typegen.png)
```

2022-06-14 11:20 UTC, laurakalbag commented on content/posts/2022-06-13-nesting-typegen-files.mdx
> +And this is how it looks after enabling file nesting for typegen files. Now it allows you to hide the generated file behind the source if you want to.
```suggestion
After enabling file nesting for typegen files, VS Code explorer allows you to nest and collapse the generated file under the source file.
```

2022-06-14 11:20 UTC, laurakalbag commented on content/posts/2022-06-13-nesting-typegen-files.mdx
> +![Animated GIF showing how it looks when you toggle nesting of a generated type file.](./images/with-typegen.gif)
```suggestion
![Pressing the arrow icon toggle alongside the source file toggles the nesting of the generated type file.](./images/with-typegen.gif)
```

2022-06-14 11:20 UTC, laurakalbag commented on content/posts/2022-06-13-nesting-typegen-files.mdx
> +If you’re using our VS Code extension and haven’t manually enabled file nesting for typegen files, you will see a helper prompt allowing you to enable file nesting with 1 click.
Does this helper prompt appear when you open VS Code for the first time after update? Or when you perform a particular action with the extension?

2022-06-15 07:32 UTC, mellson commented
Thank you for the lovely feedback @laurakalbag 🙏🏻 I agree with your comments and have updated the blog post with suggestions and more info on the prompt + how to disable file nesting.

2022-06-15 09:51 UTC, laurakalbag approved these changes
Approved with a tiny suggestion for alt text.

2022-06-15 09:51 UTC, laurakalbag commented on content/posts/2022-06-13-nesting-typegen-files.mdx
> +![The settings view in VS Code showing the settings specific for XState.](./images/xstate-vscode-settings.png)
```suggestion
![The Extensions settings view in VS Code has XState settings including the option to enable nesting the generated typegen files.](./images/xstate-vscode-settings.png)
```

2022-06-15 09:52 UTC, merged